# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dec2d260629b1a9dd06f4f6d23a410dc59ca8ab3064fc2adfe80dda2357e4db994a48ce1395dbed582d105fe6589b3a40bb7eb20e66aa25d386a238fc6c72083

test:
  secret_key_base: 3fa7d0641fa73c84a430b5074718bb177d468b1d2efcec8a690ab47a848057a2610a126a5728bce76f4be31f04af2a562de7753154945119a7bd6973c8d97f80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
